logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    com.beninexplo.backend: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
  endpoint:
    health:
      show-details: always
