--
-- PostgreSQL database dump
--

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activites (
    id_activite bigint NOT NULL,
    description character varying(5000),
    difficulte character varying(255),
    duree_interne integer,
    nom character varying(255),
    poids integer,
    image_principale_id bigint,
    ville_id bigint NOT NULL
);


--
-- Name: activites_id_activite_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activites ALTER COLUMN id_activite ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activites_id_activite_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actualite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.actualite (
    id_actualite bigint NOT NULL,
    contenu character varying(10000),
    date_publication timestamp(6) without time zone,
    titre character varying(255),
    auteur_id bigint,
    image_principale_id bigint,
    a_la_une boolean NOT NULL,
    image_url character varying(1000),
    publiee boolean NOT NULL,
    resume character varying(600)
);


--
-- Name: actualite_id_actualite_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.actualite ALTER COLUMN id_actualite ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actualite_id_actualite_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories_activites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories_activites (
    id_categorie bigint NOT NULL,
    description character varying(5000),
    nom character varying(255)
);


--
-- Name: categories_activites_id_categorie_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories_activites ALTER COLUMN id_categorie ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_activites_id_categorie_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circuit_activites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circuit_activites (
    id_circuit_activite bigint NOT NULL,
    jour_indicatif integer,
    ordre integer,
    activite_id bigint,
    circuit_id bigint
);


--
-- Name: circuit_activites_id_circuit_activite_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.circuit_activites ALTER COLUMN id_circuit_activite ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circuit_activites_id_circuit_activite_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circuit_perso_jour_activites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circuit_perso_jour_activites (
    jour_id bigint NOT NULL,
    activite_id bigint NOT NULL
);


--
-- Name: circuit_personnalise_jours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circuit_personnalise_jours (
    id bigint NOT NULL,
    description_jour character varying(2000),
    numero_jour integer NOT NULL,
    circuit_personnalise_id bigint NOT NULL,
    ville_id bigint,
    zone_id bigint
);


--
-- Name: circuit_personnalise_jours_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.circuit_personnalise_jours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circuit_personnalise_jours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circuits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circuits (
    id_circuit bigint NOT NULL,
    actif boolean NOT NULL,
    aventures text,
    description character varying(5000),
    duree_indicative character varying(255),
    formule_proposee character varying(255),
    galerie text,
    img text,
    inclus text,
    nom character varying(255),
    non_inclus text,
    points_forts text,
    prix_indicatif numeric(38,2),
    programme text,
    resume character varying(2000),
    tourisme text,
    image_principale_id bigint,
    ville_id bigint NOT NULL,
    featured_home boolean DEFAULT false NOT NULL,
    a_la_une boolean DEFAULT false NOT NULL
);


--
-- Name: circuits_id_circuit_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.circuits ALTER COLUMN id_circuit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circuits_id_circuit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circuits_personnalises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circuits_personnalises (
    id bigint NOT NULL,
    avec_chauffeur boolean NOT NULL,
    avec_guide boolean NOT NULL,
    avec_hebergement boolean NOT NULL,
    avec_transport boolean NOT NULL,
    date_creation date,
    date_voyage_souhaitee date,
    email_client character varying(255),
    message_client character varying(5000),
    nom_client character varying(255),
    nombre_jours integer NOT NULL,
    nombre_personnes integer NOT NULL,
    pension_complete boolean NOT NULL,
    prenom_client character varying(255),
    prix_estime numeric(38,2),
    prix_final numeric(38,2),
    statut character varying(255),
    telephone_client character varying(255),
    type_hebergement character varying(255),
    type_transport character varying(255),
    circuit_cree_id bigint,
    commentaire_admin character varying(5000),
    date_traitement date,
    motif_refus character varying(5000),
    CONSTRAINT circuits_personnalises_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'EN_TRAITEMENT'::character varying, 'ACCEPTE'::character varying, 'REFUSE'::character varying, 'TERMINE'::character varying])::text[])))
);


--
-- Name: circuits_personnalises_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.circuits_personnalises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circuits_personnalises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_demandes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client_demandes (
    id_demande bigint NOT NULL,
    email character varying(255),
    message character varying(10000),
    nom character varying(255),
    prenom character varying(255),
    telephone character varying(255),
    circuit_id bigint
);


--
-- Name: client_demandes_id_demande_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.client_demandes ALTER COLUMN id_demande ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_demandes_id_demande_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devis (
    id_devis bigint NOT NULL,
    email character varying(255),
    message character varying(20000),
    nom character varying(255),
    prenom character varying(255),
    telephone character varying(255),
    circuit_id bigint
);


--
-- Name: devis_activites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devis_activites (
    id bigint NOT NULL,
    quantite integer,
    activite_id bigint,
    devis_id bigint
);


--
-- Name: devis_activites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devis_activites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devis_activites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devis_id_devis_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devis ALTER COLUMN id_devis ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devis_id_devis_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hebergements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hebergements (
    id_hebergement bigint NOT NULL,
    description character varying(5000),
    image_urls text,
    localisation character varying(255),
    nom character varying(255),
    prix_par_nuit double precision NOT NULL,
    quartier character varying(255),
    type character varying(255)
);


--
-- Name: hebergements_id_hebergement_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hebergements ALTER COLUMN id_hebergement ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hebergements_id_hebergement_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medias (
    id_media bigint NOT NULL,
    description character varying(255),
    type character varying(255),
    url character varying(255)
);


--
-- Name: medias_id_media_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medias ALTER COLUMN id_media ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medias_id_media_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parametres_site; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parametres_site (
    id_parametres bigint NOT NULL,
    adresse_agence character varying(255),
    email_contact character varying(255),
    telephone_contact character varying(255)
);


--
-- Name: parametres_site_id_parametres_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parametres_site ALTER COLUMN id_parametres ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parametres_site_id_parametres_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations (
    id_reservation bigint NOT NULL,
    date_reservation date,
    email character varying(255),
    nom character varying(255),
    prenom character varying(255),
    telephone character varying(255),
    circuit_id bigint
);


--
-- Name: reservations_hebergement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations_hebergement (
    id_reservation bigint NOT NULL,
    commentaires character varying(1000),
    date_arrivee date,
    date_creation date,
    date_depart date,
    email_client character varying(255),
    nom_client character varying(255),
    nombre_nuits integer NOT NULL,
    nombre_personnes integer NOT NULL,
    prenom_client character varying(255),
    prix_total double precision NOT NULL,
    statut character varying(255),
    telephone_client character varying(255),
    id_hebergement bigint
);


--
-- Name: reservations_hebergement_id_reservation_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservations_hebergement ALTER COLUMN id_reservation ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_hebergement_id_reservation_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_id_reservation_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservations ALTER COLUMN id_reservation ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_id_reservation_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tombola_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tombola_participants (
    id bigint NOT NULL,
    date_inscription timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    nom character varying(255),
    prenom character varying(255),
    utilisateur_id bigint NOT NULL
);


--
-- Name: tombola_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tombola_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tombola_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.utilisateurs (
    id bigint NOT NULL,
    date_creation timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    mot_de_passe character varying(255),
    nom character varying(255),
    prenom character varying(255),
    role character varying(255),
    telephone character varying(255)
);


--
-- Name: utilisateurs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.utilisateurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicules (
    id bigint NOT NULL,
    annee integer NOT NULL,
    disponible boolean NOT NULL,
    marque character varying(255),
    matricule character varying(255),
    modele character varying(255)
);


--
-- Name: vehicules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehicules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: villes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.villes (
    id_ville bigint NOT NULL,
    nom character varying(255),
    zone_id bigint
);


--
-- Name: villes_id_ville_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.villes ALTER COLUMN id_ville ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.villes_id_ville_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zones (
    id_zone bigint NOT NULL,
    description character varying(255),
    nom character varying(255)
);


--
-- Name: zones_id_zone_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.zones ALTER COLUMN id_zone ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zones_id_zone_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activites activites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activites
    ADD CONSTRAINT activites_pkey PRIMARY KEY (id_activite);


--
-- Name: actualite actualite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actualite
    ADD CONSTRAINT actualite_pkey PRIMARY KEY (id_actualite);


--
-- Name: categories_activites categories_activites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories_activites
    ADD CONSTRAINT categories_activites_pkey PRIMARY KEY (id_categorie);


--
-- Name: circuit_activites circuit_activites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_activites
    ADD CONSTRAINT circuit_activites_pkey PRIMARY KEY (id_circuit_activite);


--
-- Name: circuit_personnalise_jours circuit_personnalise_jours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_personnalise_jours
    ADD CONSTRAINT circuit_personnalise_jours_pkey PRIMARY KEY (id);


--
-- Name: circuits_personnalises circuits_personnalises_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuits_personnalises
    ADD CONSTRAINT circuits_personnalises_pkey PRIMARY KEY (id);


--
-- Name: circuits circuits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuits
    ADD CONSTRAINT circuits_pkey PRIMARY KEY (id_circuit);


--
-- Name: client_demandes client_demandes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client_demandes
    ADD CONSTRAINT client_demandes_pkey PRIMARY KEY (id_demande);


--
-- Name: devis_activites devis_activites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devis_activites
    ADD CONSTRAINT devis_activites_pkey PRIMARY KEY (id);


--
-- Name: devis devis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devis
    ADD CONSTRAINT devis_pkey PRIMARY KEY (id_devis);


--
-- Name: hebergements hebergements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hebergements
    ADD CONSTRAINT hebergements_pkey PRIMARY KEY (id_hebergement);


--
-- Name: medias medias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medias
    ADD CONSTRAINT medias_pkey PRIMARY KEY (id_media);


--
-- Name: parametres_site parametres_site_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parametres_site
    ADD CONSTRAINT parametres_site_pkey PRIMARY KEY (id_parametres);


--
-- Name: reservations_hebergement reservations_hebergement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_hebergement
    ADD CONSTRAINT reservations_hebergement_pkey PRIMARY KEY (id_reservation);


--
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id_reservation);


--
-- Name: tombola_participants tombola_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tombola_participants
    ADD CONSTRAINT tombola_participants_pkey PRIMARY KEY (id);


--
-- Name: circuits_personnalises uk3vjxmba0efk7ybmfl2sndfrly; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuits_personnalises
    ADD CONSTRAINT uk3vjxmba0efk7ybmfl2sndfrly UNIQUE (circuit_cree_id);


--
-- Name: utilisateurs uk6ldvumu3hqvnmmxy1b6lsxwqy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utilisateurs
    ADD CONSTRAINT uk6ldvumu3hqvnmmxy1b6lsxwqy UNIQUE (email);


--
-- Name: utilisateurs utilisateurs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utilisateurs
    ADD CONSTRAINT utilisateurs_pkey PRIMARY KEY (id);


--
-- Name: vehicules vehicules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicules
    ADD CONSTRAINT vehicules_pkey PRIMARY KEY (id);


--
-- Name: villes villes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.villes
    ADD CONSTRAINT villes_pkey PRIMARY KEY (id_ville);


--
-- Name: zones zones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zones
    ADD CONSTRAINT zones_pkey PRIMARY KEY (id_zone);


--
-- Name: tombola_participants fk1f3bpqnhql6vd55tn6si8kaou; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tombola_participants
    ADD CONSTRAINT fk1f3bpqnhql6vd55tn6si8kaou FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateurs(id);


--
-- Name: reservations_hebergement fk1fvlpw5vge2np1bn9qugcyvf7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_hebergement
    ADD CONSTRAINT fk1fvlpw5vge2np1bn9qugcyvf7 FOREIGN KEY (id_hebergement) REFERENCES public.hebergements(id_hebergement);


--
-- Name: circuit_personnalise_jours fk3cwgm92w9sop7x56wmm2gvnp4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_personnalise_jours
    ADD CONSTRAINT fk3cwgm92w9sop7x56wmm2gvnp4 FOREIGN KEY (circuit_personnalise_id) REFERENCES public.circuits_personnalises(id);


--
-- Name: circuit_perso_jour_activites fk5utv9hnb36oyc2ynrci5g8eqo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_perso_jour_activites
    ADD CONSTRAINT fk5utv9hnb36oyc2ynrci5g8eqo FOREIGN KEY (activite_id) REFERENCES public.activites(id_activite);


--
-- Name: villes fk65it2df7lfj9w4lacqb6xlmhe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.villes
    ADD CONSTRAINT fk65it2df7lfj9w4lacqb6xlmhe FOREIGN KEY (zone_id) REFERENCES public.zones(id_zone);


--
-- Name: actualite fk7b2bekmyteldipqdt2300ylui; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actualite
    ADD CONSTRAINT fk7b2bekmyteldipqdt2300ylui FOREIGN KEY (image_principale_id) REFERENCES public.medias(id_media);


--
-- Name: devis_activites fk7d8x55mi3rpcl1heej0ye8qm3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devis_activites
    ADD CONSTRAINT fk7d8x55mi3rpcl1heej0ye8qm3 FOREIGN KEY (devis_id) REFERENCES public.devis(id_devis);


--
-- Name: circuit_perso_jour_activites fk7qcf0l8tfrplkeal7s3qopvbu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_perso_jour_activites
    ADD CONSTRAINT fk7qcf0l8tfrplkeal7s3qopvbu FOREIGN KEY (jour_id) REFERENCES public.circuit_personnalise_jours(id);


--
-- Name: circuit_activites fk9p3hf3at80ly19303odv5tpnv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_activites
    ADD CONSTRAINT fk9p3hf3at80ly19303odv5tpnv FOREIGN KEY (circuit_id) REFERENCES public.circuits(id_circuit);


--
-- Name: actualite fkbnq6aq72j2k2h8n47hrllh8eq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actualite
    ADD CONSTRAINT fkbnq6aq72j2k2h8n47hrllh8eq FOREIGN KEY (auteur_id) REFERENCES public.utilisateurs(id);


--
-- Name: devis_activites fker2he9vb0e4ggk0k78h8mdjob; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devis_activites
    ADD CONSTRAINT fker2he9vb0e4ggk0k78h8mdjob FOREIGN KEY (activite_id) REFERENCES public.activites(id_activite);


--
-- Name: activites fkfeui5u3dpf9eobumf7f7u8v5j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activites
    ADD CONSTRAINT fkfeui5u3dpf9eobumf7f7u8v5j FOREIGN KEY (ville_id) REFERENCES public.villes(id_ville);


--
-- Name: circuit_personnalise_jours fki8lab5lbdshxkrl476cqfqt2p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_personnalise_jours
    ADD CONSTRAINT fki8lab5lbdshxkrl476cqfqt2p FOREIGN KEY (ville_id) REFERENCES public.villes(id_ville);


--
-- Name: activites fkirqupcht5t29ly9cke530o10t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activites
    ADD CONSTRAINT fkirqupcht5t29ly9cke530o10t FOREIGN KEY (image_principale_id) REFERENCES public.medias(id_media);


--
-- Name: devis fkis39p7vygdp2d3ol30af7xott; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devis
    ADD CONSTRAINT fkis39p7vygdp2d3ol30af7xott FOREIGN KEY (circuit_id) REFERENCES public.circuits(id_circuit);


--
-- Name: circuits fkish58quvy4qq4io52cnnfp0iw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuits
    ADD CONSTRAINT fkish58quvy4qq4io52cnnfp0iw FOREIGN KEY (ville_id) REFERENCES public.villes(id_ville);


--
-- Name: circuit_personnalise_jours fkk74sx24s6tgs0tv3kx866ftic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_personnalise_jours
    ADD CONSTRAINT fkk74sx24s6tgs0tv3kx866ftic FOREIGN KEY (zone_id) REFERENCES public.zones(id_zone);


--
-- Name: circuit_activites fkkwvhethptwv9ncanj7lkglpxi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuit_activites
    ADD CONSTRAINT fkkwvhethptwv9ncanj7lkglpxi FOREIGN KEY (activite_id) REFERENCES public.activites(id_activite);


--
-- Name: circuits fkn2s0ejjsb0w7we6pky90pv8rg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuits
    ADD CONSTRAINT fkn2s0ejjsb0w7we6pky90pv8rg FOREIGN KEY (image_principale_id) REFERENCES public.medias(id_media);


--
-- Name: reservations fkotevttb8r1rgi6x67r70fd9kd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fkotevttb8r1rgi6x67r70fd9kd FOREIGN KEY (circuit_id) REFERENCES public.circuits(id_circuit);


--
-- Name: client_demandes fkq2jw3w86xch758b5k1lmrkxro; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client_demandes
    ADD CONSTRAINT fkq2jw3w86xch758b5k1lmrkxro FOREIGN KEY (circuit_id) REFERENCES public.circuits(id_circuit);


--
-- Name: circuits_personnalises fks81xqkfnjx0m7qyg3hs12mq4t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circuits_personnalises
    ADD CONSTRAINT fks81xqkfnjx0m7qyg3hs12mq4t FOREIGN KEY (circuit_cree_id) REFERENCES public.circuits(id_circuit);


--
-- PostgreSQL database dump complete
--

